### Register User
POST http://localhost:9090/api/auth/register
Content-Type: application/json

{
  "username": "zakariaX",
  "email": "zakaria@example.com",
  "password": "Password123"
}

### OR Login
POST http://localhost:9090/api/auth/login
Content-Type: application/json

{
  "usernameOrEmail": "zakaria@example.com",
  "password": "Password123"
}