package com.collabflow.events.model;

public enum DomainEventType {
    USER_REGISTERED,
    TEAM_MEMBER_INVITED,
    TEAM_MEMBER_JOINED,
    PROJECT_CREATED,
    PROJECT_UPDATED,
    PROJECT_DELETED,
    TASK_CREATED,
    TASK_UPDATED,
    TASK_DELETED,
    TASK_MOVED,
    CHAT_MESSAGE_SENT
}
