spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/collabflow
    username: zakaria
    password: zakaria
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
server:
  port: 9090


app:
  jwtSecret: L8f9kP2mQ5xN7vW3jR6bY9tU4sH1gD0cE+mN8pL2oK5qX7vY=
  jwtExpirationMs: 3600000
  jwtRefreshExpirationMs: 2592000000  # 30 days



