spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/collabflow
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
server:
  port: 8080
